[frontend]
frontend-vm ansible_host=FRONTEND_IP ansible_user=azureuser ansible_ssh_private_key_file=SSH_KEY_PATH ansible_ssh_common_args='-o StrictHostKeyChecking=no'

[backend]
backend-vm ansible_host=BACKEND_IP ansible_user=azureuser ansible_ssh_private_key_file=SSH_KEY_PATH ansible_ssh_common_args='-o StrictHostKeyChecking=no'