[frontend]
frontend-vm ansible_host=REPLACE_WITH_FRONTEND_IP ansible_user=azureadmin ansible_ssh_private_key_file=~/.ssh/epicbook

[backend]
backend-vm ansible_host=REPLACE_WITH_BACKEND_PRIVATE_IP ansible_user=azureadmin ansible_ssh_private_key_file=~/.ssh/epicbook

[web:children]
frontend
backend

[web:vars]
ansible_python_interpreter=/usr/bin/python3
