---
- name: Prepare system (common)
  hosts: frontend
  become: true
  roles:
    - common

- name: Install and configure Nginx
  hosts: frontend
  become: true
  roles:
    - nginx

- name: Install and configure MySQL
  hosts: frontend
  become: true
  roles:
    - mysql

- name: Deploy EpicBook application
  hosts: frontend
  become: true
  roles:
    - epicbook
